name = "my-fauna-api"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-11-21"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
